ARG NODE_VERSION

FROM golang:1.17-alpine as builder
RUN apk add --no-cache git
WORKDIR /root/
RUN go get github.com/google/pprof

FROM node:${NODE_VERSION}-alpine

ARG ADDITIONAL_PACKAGES
# Force ipv4 results first b/275122541
ENV NODE_OPTIONS="--dns-result-order=ipv4first"

RUN apk add --no-cache bash $ADDITIONAL_PACKAGES \
	# workaround needed to force ipv4 on kokoro
	&& echo "precedence ::ffff:0:0/96 100" >> /etc/gai.conf

WORKDIR /root/
COPY --from=builder /go/bin/pprof /bin
RUN chmod a+x /bin/pprof
